name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    name: Add PR labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
    
      - name: Add 'revert' label to relevant PRs
        if: contains(github.event.pull_request.title, 'Revert')
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            github.rest.issues.addLabels({
              owner, repo,
              issue_number: context.payload.pull_request.number,
              labels: ['${{ inputs.revert_label }}'],
            });


    permissions:
      actions: write
      pull-requests: write